import {
  BriefcaseBusiness,
  Building2,
  Camera,
  Cloud,
  Factory,
  Fuel,
  GraduationCap,
  HandHeart,
  HardHat,
  HeartPulse,
  Hotel,
  Landmark,
  Lightbulb,
  Pickaxe,
  Radio,
  Settings,
  ShieldCheck,
  Store,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const serviceIconMap: Record<string, LucideIcon> = {
  "telecom-infrastructure": Radio,
  "ict-solutions": Cloud,
  "nca-regulatory": ShieldCheck,
  "security-solutions": Camera,
  "power-solutions": Zap,
  "equipment-supply": Wrench,
  "managed-services": Settings,
  consultancy: Lightbulb,
};

export const industryIconMap: Record<string, LucideIcon> = {
  "Telecommunication Companies": Radio,
  "Government Institutions": Landmark,
  "Financial Institutions": BriefcaseBusiness,
  "Educational Institutions": GraduationCap,
  "Healthcare Facilities": HeartPulse,
  "Construction Companies": HardHat,
  "Real Estate Developers": Building2,
  "Hotels & Hospitality": Hotel,
  "Oil & Gas Companies": Fuel,
  "Mining Companies": Pickaxe,
  "Manufacturing Industries": Factory,
  "NGOs and Development Organizations": HandHeart,
  "Small & Medium Enterprises (SMEs)": Store,
};
